### ISSUE TITLE
No close modal

### ISSUE THREAD

**Issue by juanfeorar** [nbudin/react-bootstrap4-modal#18]
Hi,
The modal does not close.
I use bootstrap 4 in index.html through CDN and only css <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

My source is:

```
import React, { Component } from 'react';
import Modal from 'react-bootstrap4-modal';

<Modal visible={true} onClickBackdrop={this.modalBackdropClicked}>
                    <div className="modal-header">
                        <h5 className="modal-title">Red Alert!</h5>
                    </div>
                    <div className="modal-body">
                        <p>Enemy vessel approaching!</p>
                    </div>
                    <div className="modal-footer">
                        <button type="button" className="btn btn-secondary" onClick={this.onPanic}>
                            Panic
          </button>
                        <button type="button" className="btn btn-primary" onClick={this.onFirePhasers}>
                            Fire phasers
          </button>
                        <button type="button" className="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </Modal>
```

![closemodal](https://user-images.githubusercontent.com/1591202/53244908-2ec3ba80-367a-11e9-850b-516a10cfcdbc.png)

**Comment by nbudin** [comment]
This seems to be a hybrid of react-bootstrap4-modal and Bootstrap's built-in JavaScript.  `data-dismiss` won't do anything in this library, because it's the way the jQuery-based JavaScript that Bootstrap ships with has you close a modal.

The way to do it with react-bootstrap4-modal would be to make a React component and track whether or not the modal is visible as part of that component's state.  You can then pass that state for the `visible` prop on the modal, and set the state to false when the "close" button is clicked (and, potentially, when onClickBackdrop fires).

**Comment by juanfeorar** [comment]
Yes, that's how I solved it.

Thanks
