### ISSUE TITLE
DOM insertion

### ISSUE THREAD

**Issue by adamcoulombe** [nbudin/react-bootstrap4-modal#19]
I would like to use this modal component nested inside other components, a few deep.

I was wondering, is there any way to insert or attach the modal elsewhere in the DOM? If I try and use the modal inside a relative position ancestor, it doesn't go full screen, because it's positioned relative to the ancestor..

This can be inconvenient to move the component elsewhere in the application. Any thoughts on this?

**Comment by nbudin** [comment]
One way would be using [Portals](https://reactjs.org/docs/portals.html).  I think that's the way most people do this in React apps.

I'm personally using a different approach in my own app: most of the pages are almost entirely React components, so I have a container component at the root of the tree.  That container exposes a React Context that has functions for opening a modal, closing a modal, etc.  Then the modal itself is rendered by the container so that it can be at the root level of the page.  I don't think that approach makes sense for every app, and I'd encourage trying portals first, but it is working well for me.

**Comment by adamcoulombe** [comment]
Thanks for getting back to me so quickly.

Portals.... who knew! Ill give that a try, thanks!!

**Comment by adamcoulombe** [comment]
Incredible. That was super easy. Portals worked like a charm. Thanks Again @nbudin  
```
class SomeDeeplyNestedComponent extends Component {
   render() {
      return (
         <div>
            {ReactDOM.createPortal(
               <Modal visible={this.state.modalVisibility}>
                  This Modal is attached to document body
               </Modal>
            ,document.body)}
         </div>
      )
   }
}
```

**Comment by nbudin** [comment]
Awesome, glad it worked out!
