### ISSUE TITLE
Events on modal open and modal closed

### ISSUE THREAD

**Issue by bboe** [nbudin/react-bootstrap4-modal#22]
Thanks for this tool! I'm testing switching from react-model to this project. One key discrepancy appears to be that modals are mounted when declared instead of when opened. That's not necessarily an issue, however, I'd like to know the canonical way to determine when the modal is opened, and similarly when it's closed to perform. Thanks!

With react-model the triggers are `componentDidMount` and `componentWillUnmount` respectively.

**Comment by nbudin** [comment]
The idea with react-bootstrap4-modal is that you always render the Modal component, and use the `visible` prop to control whether it's shown or not.  (The reason for that is to enable the modal open/close CSS animations to work - if we actually stopped rendering the component, the markup would be removed from the page and then the modal would just disappear with no animation.)

So because it's a controlled prop, you're in control of whether the modal is open or closed from wherever you're rendering it.  Therefore you can take any actions you want whenever you change the prop - no need for an event handler.
